import kavaad as kv
import time

kv.init()


try:
    kv.led_on(0, 0, 0)
    time.sleep(3)
    kv.led_on(1, 0, 0)
    time.sleep(3)
    kv.led_on(2, 0, 0)
    time.sleep(3)
    kv.led_on(3, 0, 0)
    time.sleep(3)
    kv.led_on(4, 0, 0)
    time.sleep(3)
    kv.led_on(5, 0, 0)
    time.sleep(3)
    kv.led_on(6, 0, 0)
    time.sleep(3)
    kv.led_on(7, 0, 0)
    time.sleep(3)
    kv.led_on(8, 0, 0)
    time.sleep(3)
    kv.led_on(9, 0, 0)
    time.sleep(3)
    kv.led_on(1, 1, 1)
    time.sleep(3)

    time.sleep(3)
    kv.led_on(0, 0, 0)
    time.sleep(3)
    kv.led_on(1, 0, 0)
    time.sleep(3)
    kv.led_on(2, 0, 0)
    time.sleep(3)
    kv.led_on(3, 0, 0)
    time.sleep(3)
    kv.led_on(4, 0, 0)
    time.sleep(3)
    kv.led_on(5, 0, 0)
    time.sleep(3)
    kv.led_on(6, 0, 0)
    time.sleep(3)
    kv.led_on(7, 0, 0)
    time.sleep(3)
    kv.led_on(8, 0, 1)
    time.sleep(3)
    kv.led_on(9, 0, 1)
    time.sleep(3)
    kv.led_on(1, 1, 1)
    time.sleep(3)

    time.sleep(3)
    kv.led_on(0, 0, 0)
    time.sleep(3)
    kv.led_on(1, 0, 0)
    time.sleep(3)
    kv.led_on(2, 0, 0)
    time.sleep(3)
    kv.led_on(3, 0, 0)
    time.sleep(3)
    kv.led_on(4, 0, 0)
    time.sleep(3)
    kv.led_on(5, 1, 0)
    time.sleep(3)
    kv.led_on(6, 1, 0)
    time.sleep(3)
    kv.led_on(7, 1, 0)
    time.sleep(3)
    kv.led_on(8, 1, 0)
    time.sleep(3)
    kv.led_on(9, 1, 0)
    time.sleep(3)
    kv.led_on(1, 1, 1)
    time.sleep(3)

    time.sleep(3)
    kv.led_on(0, 0, 0)
    time.sleep(3)
    kv.led_on(1, 0, 0)
    time.sleep(3)
    kv.led_on(2, 0, 0)
    time.sleep(3)
    kv.led_on(3, 0, 0)
    time.sleep(3)
    kv.led_on(4, 0, 0)
    time.sleep(3)
    kv.led_on(5, 1, 0)
    time.sleep(3)
    kv.led_on(6, 1, 0)
    time.sleep(3)
    kv.led_on(7, 1, 0)
    time.sleep(3)
    kv.led_on(8, 1, 1)
    time.sleep(3)
    kv.led_on(9, 1, 1)
    time.sleep(3)
    kv.led_on(1, 1, 1)
    time.sleep(3)


except KeyboardInterrupt:
    print("Keyboard Interrupt")
finally:
    kv.cleanup()
